/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GalaxyRouteImport } from './routes/galaxy'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClassroomsRouteImport } from './routes/classrooms'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassroomsClassroomIdRouteImport } from './routes/classrooms.$classroomId'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GalaxyRoute = GalaxyRouteImport.update({
  id: '/galaxy',
  path: '/galaxy',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomsRoute = ClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomsClassroomIdRoute = ClassroomsClassroomIdRouteImport.update({
  id: '/$classroomId',
  path: '/$classroomId',
  getParentRoute: () => ClassroomsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classrooms': typeof ClassroomsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/galaxy': typeof GalaxyRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/track': typeof TrackRoute
  '/classrooms/$classroomId': typeof ClassroomsClassroomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classrooms': typeof ClassroomsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/galaxy': typeof GalaxyRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/track': typeof TrackRoute
  '/classrooms/$classroomId': typeof ClassroomsClassroomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classrooms': typeof ClassroomsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/galaxy': typeof GalaxyRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/track': typeof TrackRoute
  '/classrooms/$classroomId': typeof ClassroomsClassroomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/classrooms'
    | '/dashboard'
    | '/demo'
    | '/galaxy'
    | '/learn'
    | '/login'
    | '/settings'
    | '/signup'
    | '/student'
    | '/track'
    | '/classrooms/$classroomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/classrooms'
    | '/dashboard'
    | '/demo'
    | '/galaxy'
    | '/learn'
    | '/login'
    | '/settings'
    | '/signup'
    | '/student'
    | '/track'
    | '/classrooms/$classroomId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/classrooms'
    | '/dashboard'
    | '/demo'
    | '/galaxy'
    | '/learn'
    | '/login'
    | '/settings'
    | '/signup'
    | '/student'
    | '/track'
    | '/classrooms/$classroomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClassroomsRoute: typeof ClassroomsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  GalaxyRoute: typeof GalaxyRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galaxy': {
      id: '/galaxy'
      path: '/galaxy'
      fullPath: '/galaxy'
      preLoaderRoute: typeof GalaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classrooms': {
      id: '/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof ClassroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classrooms/$classroomId': {
      id: '/classrooms/$classroomId'
      path: '/$classroomId'
      fullPath: '/classrooms/$classroomId'
      preLoaderRoute: typeof ClassroomsClassroomIdRouteImport
      parentRoute: typeof ClassroomsRoute
    }
  }
}

interface ClassroomsRouteChildren {
  ClassroomsClassroomIdRoute: typeof ClassroomsClassroomIdRoute
}

const ClassroomsRouteChildren: ClassroomsRouteChildren = {
  ClassroomsClassroomIdRoute: ClassroomsClassroomIdRoute,
}

const ClassroomsRouteWithChildren = ClassroomsRoute._addFileChildren(
  ClassroomsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClassroomsRoute: ClassroomsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  GalaxyRoute: GalaxyRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
